---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tibble)
source('PitchControl.R')
```

```{r}
space=read.csv('AnalyzedData/spaceValueSource.csv',row.names = 1)
```

```{r}
space1=add_column(space, d=NA, .after = 178)
space1=add_column(space1, an=NA, .after = 178)
space1=add_column(space1, d1=NA, .after = 171)
space1=add_column(space1, an1=NA, .after = 171)
space1=add_column(space1, d2=NA, .after = 164)
space1=add_column(space1, an2=NA, .after = 164)
space1=add_column(space1, d3=NA, .after = 157)
space1=add_column(space1, an3=NA, .after = 157)
space1=add_column(space1, d4=NA, .after = 150)
space1=add_column(space1, an4=NA, .after = 150)
space1=add_column(space1, d5=NA, .after = 143)
space1=add_column(space1, an5=NA, .after = 143)
space1=add_column(space1, d6=NA, .after = 136)
space1=add_column(space1, an6=NA, .after = 136)
space1=add_column(space1, d7=NA, .after = 129)
space1=add_column(space1, an7=NA, .after = 129)
space1=add_column(space1, d8=NA, .after = 122)
space1=add_column(space1, an8=NA, .after = 122)
space1=add_column(space1, d9=NA, .after = 115)
space1=add_column(space1, an9=NA, .after = 115)
space1=add_column(space1, d10=NA, .after = 108)
space1=add_column(space1, an10=NA, .after = 108)
space1=add_column(space1, d11=NA, .after = 101)
space1=add_column(space1, an11=NA, .after = 101)
space1=add_column(space1, d12=NA, .after = 94)
space1=add_column(space1, an12=NA, .after = 94)
space1=add_column(space1, d13=NA, .after = 87)
space1=add_column(space1, an13=NA, .after = 87)
space1=add_column(space1, d14=NA, .after = 80)
space1=add_column(space1, an14=NA, .after = 80)
space1=add_column(space1, d15=NA, .after = 73)
space1=add_column(space1, an15=NA, .after = 73)
space1=add_column(space1, d16=NA, .after = 66)
space1=add_column(space1, an16=NA, .after = 66)
space1=add_column(space1, d17=NA, .after = 59)
space1=add_column(space1, an17=NA, .after = 59)
space1=add_column(space1, d18=NA, .after = 52)
space1=add_column(space1, an18=NA, .after = 52)
space1=add_column(space1, d19=NA, .after = 45)
space1=add_column(space1, an19=NA, .after = 45)
space1=add_column(space1, d20=NA, .after = 38)
space1=add_column(space1, an20=NA, .after = 38)
```

```{r}
#calculate distance and angle
returner_x=space1$X24
returner_y=space1$X25
d_col=seq.int(40,220,by=9)
an_col=seq.int(39,219,by=9)
x_col=seq.int(32,212, by=9)
y_col=seq.int(33,213,by=9)
for(a in 1:length(d_col)){
  d=d_col[a]
  an=an_col[a]
  x=x_col[a]
  y=y_col[a]
  x_diff=space1[x]-returner_x
  y_diff=space1[y]-returner_y
  space1[d]=sqrt(x_diff^2+y_diff^2)
  space1[an]=atan((space1[x]-returner_x)/(space1[y]-returner_y)) #need further review
  for(b in 1:nrow(space1[an])){
    if(x_diff[b, ]>=0 & y_diff[b, ]<=0){
      space1[an][b, ]=pi+space1[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]>0){
      space1[an][b, ]=2*pi+space1[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]<=0){
      space1[an][b, ]=pi+space1[an][b, ]
    }
  }
}
```

```{r}
#flip upside down(rotate about y axis)
space2=space1
x_col=seq.int(32,212, by=9)
x_col=c(25, x_col)
y_col=seq.int(33,213, by=9)
y_col=c(26, y_col)
o_col=seq.int(37,220, by=9)
o_col=c(30, o_col)#add dir
dir_col=seq.int(38,220,by=9)
dir_col=c(31,dir_col)
for(a in 1:length(o_col)){
  o=o_col[a]
  x=x_col[a]
  dire=dir_col[a]
  space2[o]=360-space2[o]
  space2[x]=120-space2[x]
  space2[dire]=360-space2[dire]
}
returner_x=space2$X24
returner_y=space2$X25
d_col=seq.int(40,220,by=9)
an_col=seq.int(39,219,by=9)
x_col=seq.int(32,212, by=9)
y_col=seq.int(33,213,by=9)
for(a in 1:length(d_col)){
  d=d_col[a]
  an=an_col[a]
  x=x_col[a]
  y=y_col[a]
  x_diff=space2[x]-returner_x
  y_diff=space2[y]-returner_y
  space2[an]=atan((space2[x]-returner_x)/(space2[y]-returner_y)) #need further review
    for(b in 1:nrow(space2[an])){
    if(x_diff[b, ]>=0 & y_diff[b, ]<=0){
      space2[an][b, ]=pi+space2[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]>0){
      space2[an][b, ]=2*pi+space2[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]<=0){
      space2[an][b, ]=pi+space2[an][b, ]
    }
  }
}
```

```{r}
#flip left side right(rotate about x axis)
space3=rbind(space1, space2)
x_col=seq.int(32,212, by=9)
x_col=c(25, x_col)
y_col=seq.int(33,213,by=9)
y_col=c(26, y_col)
o_col=seq.int(37,220, by=9)
o_col=c(30, o_col)
dir_col=seq.int(38,220,by=9)
dir_col=c(31,dir_col)

for(a in 1:length(o_col)){
  o=o_col[a]
  o_vec=space3[o]
  y=y_col[a]
  space3[y]=53.3333-space3[y]
  dire=dir_col[a]
  dir_vec=space3[dire]
  returner_x=space3$X24
  returner_y=space3$X25
  for(b in 1:nrow(o_vec)){
    if(o_vec[b, ]<180){
      o_vec[b, ]=180-o_vec[b, ]
    }
    else{
      o_vec[b, ]=540-o_vec[b, ]
    }
    space3[o]=o_vec
  }
  
  for(c in 1:nrow(dir_vec)){
    if(dir_vec[b, ]<180){
      dir_vec[b, ]=180-dir_vec[b, ]
    }
    else{
      dir_vec[b, ]=540-dir_vec[b, ]
    }
    space3[dire]=dir_vec
  }
}

d_col=seq.int(40,220,by=9)
an_col=seq.int(39,219,by=9)
x_col=seq.int(32,212, by=9)
y_col=seq.int(33,213,by=9)
for(a in 1:length(d_col)){
  d=d_col[a]
  an=an_col[a]
  x=x_col[a]
  y=y_col[a]
  x_diff=space3[x]-returner_x
  y_diff=space3[y]-returner_y
  space3[an]=atan((space3[x]-returner_x)/(space3[y]-returner_y)) #need further review
    for(b in 1:nrow(space3[an])){
    if(x_diff[b, ]>=0 & y_diff[b, ]<=0){
      space3[an][b, ]=pi+space3[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]>0){
      space3[an][b, ]=2*pi+space3[an][b, ]
    }
    else if(x_diff[b, ]<0 & y_diff[b, ]<=0){
      space3[an][b, ]=pi+space3[an][b, ]
    }
  }
}
```

```{r}
big=rbind(space1,space2)
biggg=rbind(space1, space2, space3)
```

```{r}
nn=read.csv('AnalyzedData/nnDataSource.csv')
```

```{r}
#add tackler information
big$t1=0.0
big$t2=0.0
big$t3=0.0
big$t4=0.0
big$t5=0.0
big$t6=0.0
big$t7=0.0
big$t8=0.0
big$t9=0.0
big$t10=0.0
big$t11=0.0
biggg$t1=0.0
biggg$t2=0.0
biggg$t3=0.0
biggg$t4=0.0
biggg$t5=0.0
biggg$t6=0.0
biggg$t7=0.0
biggg$t8=0.0
biggg$t9=0.0
biggg$t10=0.0
biggg$t11=0.0
```

```{r}
big_t_matrix=big[1:7120, 221:231]#tackler identification
tId_matrix=big[1:7120, 14:24]# all tackler id
tackler=nn[5]#list of tacklers
t_index=rep(NA, nrow(tackler))
for(a in 1:nrow(tackler)){
  t_one_frame=tId_matrix[a, ]
  tackler_id=tackler[a, ]
  index=match(tackler_id, t_one_frame)
  t_index[a]=index
}
for(a in 1:nrow(big_t_matrix)){
  index=t_index[a]
  big_t_matrix[a, index]=1.0
}
```

```{r}
big1=big
biggg1=biggg
big1[1:7120,221:231]=big_t_matrix
big1[7121:14240, 221:231]=big_t_matrix
biggg1[1:7120,221:231]=big_t_matrix
biggg1[7121:14240, 221:231]=big_t_matrix
biggg1[14241:21360,221:231]=big_t_matrix
biggg1[21361:28480, 221:231]=big_t_matrix
```

```{r}
nn_t=nn$X18
big1$ts=NA
big1$ts[1:7120]=nn_t
big1$ts[7121:14240]=nn_t
biggg1$ts[1:7120]=nn_t
biggg1$ts[7121:14240]=nn_t
biggg1$ts[14241:21360]=nn_t
biggg1$ts[21361:28480]=nn_t
```

```{r}
ss=data.frame(matrix(NA, nrow=nrow(big1), ncol=21))
for(a in 1:10){
  for(b in 1:nrow(big1)){
 ss[b, a]=compute_influence(big1[b, 25],big1[b, 26],big1[b, 25],big1[b, 26], big1[b, 9*a+23], big1[b, 9*a+24], big1[b, 9*a+25], big1[b, 9*a+28])
  }
}
for(a in 11:21){
  for(b in 1:nrow(big1)){
 ss[b, a]=-compute_influence(big1[b, 25],big1[b, 26],big1[b, 25],big1[b, 26], big1[b, 9*a+23], big1[b, 9*a+24], big1[b, 9*a+25], big1[b, 9*a+28])
  }
}
```

```{r}
big2=add_column(big1, ss1=NA, .after = 220)
big2=add_column(big2, ss2=NA, .after = 211)
big2=add_column(big2, ss3=NA, .after = 202)
big2=add_column(big2, ss4=NA, .after = 193)
big2=add_column(big2, ss5=NA, .after = 184)
big2=add_column(big2, ss6=NA, .after = 175)
big2=add_column(big2, ss7=NA, .after = 166)
big2=add_column(big2, ss8=NA, .after = 157)
big2=add_column(big2, ss9=NA, .after = 148)
big2=add_column(big2, ss10=NA, .after = 139)
big2=add_column(big2, ss11=NA, .after = 130)
big2=add_column(big2, ss12=NA, .after = 121)
big2=add_column(big2, ss13=NA, .after = 112)
big2=add_column(big2, ss14=NA, .after = 103)
big2=add_column(big2, ss15=NA, .after = 94)
big2=add_column(big2, ss16=NA, .after = 85)
big2=add_column(big2, ss17=NA, .after = 76)
big2=add_column(big2, ss18=NA, .after = 67)
big2=add_column(big2, ss19=NA, .after = 58)
big2=add_column(big2, ss20=NA, .after = 49)
big2=add_column(big2, ss21=NA, .after = 40)
```

```{r}
for(a in 1:21){
  big2[a*10+31]=ss[a]
}
```

```{r}
ss=data.frame(matrix(NA, nrow=nrow(biggg1), ncol=21))
for(a in 1:10){
  for(b in 1:nrow(biggg1)){
 ss[b, a]=compute_influence(biggg1[b, 25],biggg1[b, 26],biggg1[b, 25],biggg1[b, 26], biggg1[b, 9*a+23], biggg1[b, 9*a+24], biggg1[b, 9*a+25], biggg1[b, 9*a+28])
  }
}
for(a in 11:21){
  for(b in 1:nrow(biggg1)){
 ss[b, a]=-compute_influence(biggg1[b, 25],biggg1[b, 26],biggg1[b, 25],biggg1[b, 26], biggg1[b, 9*a+23], biggg1[b, 9*a+24], biggg1[b, 9*a+25], biggg1[b, 9*a+28])
  }
}
```

```{r}
biggg2=add_column(biggg1, ss1=NA, .after = 220)
biggg2=add_column(biggg2, ss2=NA, .after = 211)
biggg2=add_column(biggg2, ss3=NA, .after = 202)
biggg2=add_column(biggg2, ss4=NA, .after = 193)
biggg2=add_column(biggg2, ss5=NA, .after = 184)
biggg2=add_column(biggg2, ss6=NA, .after = 175)
biggg2=add_column(biggg2, ss7=NA, .after = 166)
biggg2=add_column(biggg2, ss8=NA, .after = 157)
biggg2=add_column(biggg2, ss9=NA, .after = 148)
biggg2=add_column(biggg2, ss10=NA, .after = 139)
biggg2=add_column(biggg2, ss11=NA, .after = 130)
biggg2=add_column(biggg2, ss12=NA, .after = 121)
biggg2=add_column(biggg2, ss13=NA, .after = 112)
biggg2=add_column(biggg2, ss14=NA, .after = 103)
biggg2=add_column(biggg2, ss15=NA, .after = 94)
biggg2=add_column(biggg2, ss16=NA, .after = 85)
biggg2=add_column(biggg2, ss17=NA, .after = 76)
biggg2=add_column(biggg2, ss18=NA, .after = 67)
biggg2=add_column(biggg2, ss19=NA, .after = 58)
biggg2=add_column(biggg2, ss20=NA, .after = 49)
biggg2=add_column(biggg2, ss21=NA, .after = 40)
```

```{r}
for(a in 1:21){
  biggg2[a*10+31]=ss[a]
}
```

```{r}
write.csv(big2, 'AnalyzedData/big.csv')
write.csv(biggg2, 'AnalyzedData/biggg.csv')
```