---
title: "Untitled"
output: html_document
---
Tackle Breaking 


```{r}
library(stringr)
library('ggplot2')
library('gganimate')
library('cowplot')
library('png')
library('gifski')
library(dplyr)
library('tidyverse') 
library('lubridate') 
library('beeswarm')  
library('gganimate') 
library('ggridges')  
library('tidyr')
```

```{r}
players=read.csv('players.csv')
plays=read.csv('plays.csv')
PFF_2018=read.csv('PFFScoutingData.csv')
t_2018=read.csv('tracking2018.csv')
games_2018=read.csv('games.csv')
```
selecting punt plays only and give each play an unique id "playcombination"
```{r}
plays_punt_2018=plays[plays$specialTeamsPlayType=='Punt',]
plays_punt_2018$playcombination=paste(plays_punt_2018$playId, plays_punt_2018$gameId, sep='')
t_2018$playcombination=paste(t_2018$playId, t_2018$gameId, sep='')
t_2018_punt=subset(t_2018, t_2018$playcombination%in%plays_punt_2018$playcombination)
```

only cares about punt plays after received
```{r}
plays_punt_returned_2018=plays_punt_2018[plays_punt_2018$specialTeamsResult=="Return", ]
t_2018_punt=subset(t_2018_punt, t_2018_punt$playcombination%in%plays_punt_returned_2018$playcombination)
t_2018_punt$row_number=c(1:nrow(t_2018_punt))
```


```{r}
t_2018_punt$received_label=0
received_punt=subset(t_2018_punt, t_2018_punt$event=='punt_received' |t_2018_punt$frameId==1)
list_interval=list()
for (a in (1:37305)){
  beginning=received_punt[a, ]$row_number
  end=received_punt[a+1, ]$row_number-1
  interval=c(beginning:end)
  if(a==1){
    list_interval[[a]]=interval
  }
  else{
    list_interval[[length(list_interval)+1]]=interval
  }
  }
```
```{r}
for (a in 1:length(list_interval)){
  if (a%%2==1){
    t_2018_punt[list_interval[[a]], ]$received_label=0
  }
  else{
    t_2018_punt[list_interval[[a]], ]$received_label=1
  }
}
```
```{r}
t_2018_punt_received=t_2018_punt[t_2018_punt$received_label==1, ]
```

```{r}
```